export const ACL = {
    version: 3,
    features: {
        'page.home': '页面-首页',
        'page.safetyCheck': '页面-安全自查（未测评）',
        'page.report': '页面-评估报告',
        'page.appointment': '页面-预约服务',
        'page.service': '页面-服务',
        'page.deviceDetail': '页面-设备详情',
        'page.familyProfile': '页面-家庭档案',
        'page.message': '页面-消息',
        'btn.goSafetyCheck': '按钮-进入安全自查',
        'btn.startSafetyCheck': '按钮-开始自查',
        'btn.viewReport': '按钮-查看报告',
        'btn.makeAppointment': '按钮-发起预约',
        'btn.bindDevice': '按钮-绑定设备',
        'btn.deviceAdmin': '按钮-设备管理',
        'btn.alarmEntry': '按钮-告警入口',
        'btn.deviceEntry': '按钮-设备入口',
        'btn.deviceBatch': '按钮-设备批量操作',
        'btn.deviceEdit': '按钮-设备管理操作',
        'btn.deviceRename': '按钮-设备重命名',
        'btn.deviceUnbind': '按钮-设备解绑',
        'btn.deviceTransfer': '按钮-设备转让',
        'btn.familyAddMember': '按钮-家庭添加成员',
        'btn.familyRemoveMember': '按钮-家庭删除成员',
        'btn.familyEdit': '按钮-家庭编辑',
        'btn.familyTransferDeviceAdmin': '按钮-家庭转让设备权限',
        'btn.familyManage': '按钮-家庭管理入口',
        'btn.helpCenter': '按钮-帮助中心',
        'field.elderName': '字段-老人姓名',
        'field.elderIdCard': '字段-老人身份证',
        'field.elderPhone': '字段-老人手机号',
        'field.address': '字段-住址',
    },
    matrix: {
        VISITOR: {
            allow: [
                'page.home',
                'page.safetyCheck',
                'page.appointment',
                'page.service',
                'btn.goSafetyCheck',
                'btn.startSafetyCheck',
                'btn.makeAppointment',
                'btn.helpCenter',
                'field.elderName',
            ],
        },
        LEAD: {
            allow: [
                'page.home',
                'page.safetyCheck',
                'page.appointment',
                'page.service',
                'page.deviceDetail',
                'btn.goSafetyCheck',
                'btn.startSafetyCheck',
                'btn.makeAppointment',
                'btn.bindDevice',
                'btn.deviceEntry',
                'btn.alarmEntry',
                'btn.helpCenter',
                'field.elderName',
            ],
        },
        CUSTOMER: { allow: ['page.*', 'btn.*', 'field.*'] },
        OPERATOR: { allow: ['page.*', 'btn.*', 'field.*'] },
        ADMIN: { allow: ['page.*', 'btn.*', 'field.*'] },
    },
};
